set(appName "engge")
set(appVersionMajor 0)
set(appVersionMinor 8)
set(appVersionPatch 0)
set(appVersionSuffix "beta")
set(appVersion "${appVersionMajor}.${appVersionMinor}.${appVersionPatch}-${appVersionSuffix}")
